version: "3"

services:
  nodeosd:
    image: eosio/eos-dev
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888 --plugin=eosio::chain_api_plugin --plugin=eosio::history_api_plugin --plugin=eosio::net_api_plugin --http-validate-host=false --access-control-allow-origin=* --access-control-allow-headers=true
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
      - ./contracts:/contracts/usr
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  keosd:
    image: eosio/eos-dev
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=0.0.0.0:8900 --http-alias=keosd:8900 --http-alias=localhost:8900 --http-alias=127.0.0.1:8900 --http-validate-host=false --access-control-allow-origin=* --access-control-allow-headers=true
    hostname: keosd
    ports:
      - 8900:8900
    expose:
      - "8900"
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
      - ./contracts:/contracts/usr
    stop_grace_period: 10m

volumes:
  nodeos-data-volume:
  keosd-data-volume:
